### PR TITLE
add detached CLI option

### PR DESCRIPTION
**Pull request by adamcstephens**

### CODE REVIEW

**Review by srid — CHANGES_REQUESTED** [review]
Thanks. Could you fix the build?

**Comment by adamcstephens** [comment]
oops, I moved the option after testing because I realized it wasn't in order and messed up the syntax. Ran the CI tests locally, so hopefully will pass in GHA now.

**Comment by VanCoding** [comment]
Doesn't adding this flag break the "down" subcommand again? That's the whole reason why we've removed it and all other "up" arguments. Discussion is here: https://github.com/Platonic-Systems/process-compose-flake/pull/82

I mean, I'm happy the "detached" option is back, but if "down" doesn't work, how can we stop the processes?

**Comment by srid** [comment]
Huh, good catch. #83 would have caught this.

**Comment by adamcstephens** [comment]
I guess I just won't use the wrapper then, and will use process-compose directly with the generated config. Though the wrapper could maybe conditionally expose the CLI args depending on if it's an up event or not.

**Comment by srid** [comment]
@adamcstephens You can still use wrapper, like this:

```
nix run . up --detached
```

i.e., you need to pass the subcommand (`up`) explicitly.

**Pull request merged**
