### PR TITLE
Add `fromFlakeRoot` option, start processes in `$FLAKE_ROOT` by default.

### PR DESCRIPTION
**Pull request by MrFoxPro**

### CODE REVIEW

**Comment by MrFoxPro** [comment]
Maybe warn if `$FLAKE_ROOT` wasn't found? Not sure how to implement that warn message

**Comment by srid** [comment]
Could you state the real-world use case where you need this? Let me think about the problem first, before getting to the solution.

**Comment by MrFoxPro** [comment]
>


> Is this for #25 (which I didn't entirely understand)?
> 
> The problem with this PR is that it will work in some cases (eg: devShell), but not in other cases (eg: `nix run`). Unless you disable auto wiring (#27), don't add `packages.*` and say "My process-compose configuration is meant to work only in the devShell"

no, it's not for #25. 
The problem I encountered: in monorepo I splitted my `flake.nix` in different files and placed them in subdirectories. For each project I defined custom processes, and, when suddenly PWD changes, this processes doesn't start, e.g.:
./deno/web/web-deno.nix
```nix
let
  cwd = "./deno/web";
in
process-compose."dev:web-deno".settings.processes.web = {
  command = "exec deno run -A --node-modules-dir npm:vite";
  working_dir = cwd;
};
```

in root `flake.nix`:
```
imports = with inputs; [
  flake-root.flakeModule
  devenv.flakeModule
  treefmt-nix.flakeModule
  process-compose-flake.flakeModule
  ./deno/api/api-deno.nix
  ./deno/web/web-deno.nix

  ./node/web/web-node.nix
];
```

**Comment by MrFoxPro** [comment]
I'm not sure, but maybe in case of `nix run` it will by default run in place, where flake.nix is located?

**Comment by srid** [comment]
So it is a devShell only process? 

One way to solve this is to use it in combination with https://github.com/Platonic-Systems/mission-control which does support FLAKE_ROOT (unless `cdToProjectRoot` is set to false). Eg.: https://github.com/nammayatri/nammayatri/blob/493302e23ca968146eaaf90a7b8908057faab688/Backend/nix/scripts.nix#L40-L76

Is this solution sufficient?

**Comment by srid** [comment]
> I'm not sure, but maybe in case of `nix run` it will run by default in place, where flake.nix is located?

You can run `nix run github:MrFoxPro/somerepo` from anywhere with no source checked out. If there is a flake package or app, in general we would expect it to work without requiring the source tree.

**Comment by MrFoxPro** [comment]
> So it is a devShell only process?
> 
> One way to solve this is to use it in combination with https://github.com/Platonic-Systems/mission-control which does support FLAKE_ROOT (unless `cdToProjectRoot` is set to false). Eg.: https://github.com/nammayatri/nammayatri/blob/493302e23ca968146eaaf90a7b8908057faab688/Backend/nix/scripts.nix#L40-L76
> 
> Is this solution sufficient?

Not sure, I took process-compose especially to run multiple commands in parallel.


> > I'm not sure, but maybe in case of `nix run` it will run by default in place, where flake.nix is located?
> 
> You can run `nix run github:MrFoxPro/somerepo` from anywhere with no source checked out. If there is a flake package or app, in general we would expect it to work at runtime without requiring the source tree.
Yeah, if you mean that running package that is produced by `config.process-compose.<name>.outputs.package`, I can also add `inPureEvalMode`, but.... I'm stuck. Maybe I should use composing devshells, but I can't imagine how to do it when `devenv` is configured in `flake.nix`

**Comment by srid** [comment]
> Not sure, I took process-compose especially to run multiple commands in parallel.

It does.

Here's a simple example https://github.com/srid/ema-template/blob/master/flake.nix

Line 55 defines the process-compose group. 
```nix
        process-compose.run = {
          tui = false;
          settings.processes = {
            haskell.command = "ghcid";
            tailwind.command = "${lib.getExe pkgs.haskellPackages.tailwind} -w -o ./static/tailwind.css './src/**/*.hs'";
          };
        };
```

Then line 82 uses it from mission-control,
```nix
          run = {
            description = "Run the dev server (ghcid + tailwind)";
            exec = config.process-compose.run.outputs.package;
          };
```

That last part provides `, run` command in devShell, which you can run from **any** subdirectory; it will always cd to flake-root.

Let me think about this. Meanwhile, your PR can be improved to directly use the package as well, cf. https://github.com/srid/proc-flake/blob/676b5af467e52c06aa8a9165edb3345c6dbbabde/flake-module.nix#L53-L54

> Maybe I should use composing devshells, but I can't imagine how to do it when `devenv` is configured in `flake.nix`

Is your `flake.nix` available somewhere publicly?

**Comment by MrFoxPro** [comment]
Yep, so mission-control could be used together. Nice!

Thanks, I opened here: 
https://github.com/MrFoxPro/sferadel/blob/dev/flake.nix
https://github.com/MrFoxPro/sferadel/blob/dev/deno/web/web-deno.nix

**Comment by MrFoxPro** [comment]
Nushell supports this: `with-env { PWD: "/home/foxpro/craft/sferadel/next/deno" } { ls }`
Not sure how to implement it in other shells

**Comment by MrFoxPro** [comment]
I mean, how it's supposed to work outside of devshell anyway? Does process-compose use `$(dirname "$0")` or something to locate it current root, and then resolve relative `working_dir` against that root?

**Comment by MrFoxPro** [comment]
I can do this:
```nix
${if !lib.inPureEvalMode && config.fromFlakeRoot then "[[ -n $FLAKE_ROOT ]] && cd \"$FLAKE_ROOT\"" else "echo 'Warning: $FLAKE_ROOT' is not defined, script will start agains you current CWD" }
```

**Comment by MrFoxPro** [comment]
> Let me think about this. Meanwhile, your PR can be improved to directly use the package as well, cf. https://github.com/srid/proc-flake/blob/676b5af467e52c06aa8a9165edb3345c6dbbabde/flake-module.nix#L53-L54

Can't access global flake config from `default.nix`. `config` argument in `default.nix`
:
```
trace: {
  _module = {
    args = {…};
    check = true;
    freeformType = null;
    specialArgs = {…};
  };
  debug = false;
  fromFlakeRoot = true;
  outputs = {
    check = null;
    package = {…};
    settingsYaml = {…};
    upCommandArgs = " ";
  };
  package = <derivation process-compose-0.51.4>;
  port = null;
  settings = {
    environment = null;
    log_length = null;
    log_level = null;
    log_location = null;
    processes = {…};
    shell = {…};
    version = null;
  };
  testScript = null;
  tui = null;
}
```

**Comment by MrFoxPro** [comment]
Now there is strange thing:

```nix
process-compose."dev:web-node".settings = {
  processes.web = {
    command = "ls; echo $PWD; echo $(pwd)";
    working_dir = "./node/web";
  };
};
```
```
foxpro:~/craft/sferadel/next$ dev:web-node                                                                                                                                                         
...<shows content of /home/foxpro/craft/sferadel/next/node/web>
[web_1  ] /home/foxpro/craft/sferadel/next <- $PWD
[web_1  ] /home/foxpro/craft/sferadel/next/node/web <- $(pwd)
```

**Comment by srid** [comment]
> So it is a devShell only process?
> 
> One way to solve this is to use it in combination with https://github.com/Platonic-Systems/mission-control which does support FLAKE_ROOT (unless `cdToProjectRoot` is set to false). Eg.: https://github.com/nammayatri/nammayatri/blob/493302e23ca968146eaaf90a7b8908057faab688/Backend/nix/scripts.nix#L40-L76
> 
> Is this solution sufficient?

Closing per this ^

**Pull request closed without merging**
